baseurl: https://alexandrevicenzi.com/
languageCode: en
title: Alexandre Vicenzi
theme: soho
summarylength: 10
paginate: 10

enableEmoji: true
enableRobotsTXT: true

googleAnalytics: UA-55543164-1
disqusShortname: alexandrevicenziblog

params:
  mainSections:
    - posts

  images:
    - https://www.gravatar.com/avatar/5dc5ba59a94eeab2106ad9d397361b2c?s=400&d=mp

  author: Alexandre Vicenzi
  description: Software Engineer
  # themeColor: "#fc2803"
  # description:
  gravatar: blog@alexandrevicenzi.com

  copyright: Alexandre Vicenzi
  license: CC BY-SA 4.0
  licenseURL: https://creativecommons.org/licenses/by-sa/4.0

  socialIcons:
    - icon: fa-linkedin
      title: Linkedin
      url: https://www.linkedin.com/in/alexandrevicenzi
    - icon: fa-github
      title: GitHub
      url: https://github.com/alexandrevicenzi
    - icon: fa-twitter
      title: Twitter
      url: https://twitter.com/alxvicenzi
    - icon: fa-speaker-deck
      title: SpeakerDeck
      url: https://speakerdeck.com/alexandrevicenzi

  customCss:
    - 'css/blog.css'

  # customJs:
  #   - '#'

taxonomies:
  category: categories
  series: series
  tag: tags

menu:
  main:
  # - name: Posts
  #   weight: 100
  #   identifier: posts
  #   url: /posts/
  - name: Donate
    identifier: donate
    weight: 200
    url: /donate/
  - name: About Me
    identifier: about
    weight: 300
    url: /about-me/

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: github
    tabWidth: 4
